### ISSUE TITLE
Other frontmatter parameter error while editing in Expert mode

### ISSUE THREAD

**Issue by reachcontent** [getgrav/grav-skeleton-deliver-site#10]
Don't know if this is linked to the previous issue (#9) but it reminded me of it.
This occurred specifically while trying to edit in Expert mode the "Page not found template": attempt to save triggered an error with this message.

> > > > Validation failed: Invalid input in "Robots""

The incriminated bit in Frontmatter:

> title: Page not Found
> robots: noindex,nofollow
> body_classes: "modular header-lite fullwidth error"
> template: error
> routable: false
> http_response_code: 404

The point is that editing in Normal mode works ok, and seems to then generate this updated Frontmatter:

> title: 'Page not Found'
> process:
> 
> > ```
> > markdown: true
> > twig: true
> > ```
> 
> robots:
> 
> > ```
> > noindex: false
> > nofollow: false
> > ```
> 
> routable: false
> child_type: default
> body_classes: 'modular header-lite fullwidth error'
> template: error
> http_response_code: 404

**Comment by hexplor** [comment]
Yeah, probably robots variable changed with syntax as well.
