### ISSUE TITLE
Search boxes adding a character ( question mark ) to search string

### ISSUE THREAD

**Issue by davidtew** [getgrav/grav-skeleton-deliver-site#11]
Search works OK the first time you use it but thereafter the ? character is added to the search URL so searches not longer work. (search works OK if I edit the URL search string)

**Comment by hexplor** [comment]
Fixed in theme (develop) https://github.com/getgrav/grav-theme-deliver/commit/da317076418aa240401c28c57e628adf9d7ee9f7
