### ISSUE TITLE
Simpleform instructions unclear, or not working

### ISSUE THREAD

**Issue by davidtew** [getgrav/grav-skeleton-deliver-site#3]
I can get the simpleform to work, using the simpleform service, only by adding the service API key directly into the yaml file.  (I could not get it to work adding the key to the .md file ... or I was putting it in the wrong place or format within the md file perhaps?)

**Comment by hexplor** [comment]
Can't confirm that. You should put token inside: /user/pages/07.contact/_main/contact.md . Remember that you can also copy simple_form.yaml to user/config/plugins and configure it the way you want.
