### ISSUE TITLE
Quick Links 404 Error

### ISSUE THREAD

**Issue by HOFB2015** [getgrav/grav-skeleton-deliver-site#4]
Go to http://demo.getgrav.org/deliver-skeleton/blog/focus-and-blur

At the bottom of the page you have the Quicklinks in the footer from this page those links are all broken. They work on other pages 2nd level pages but not 3rd level pages. Seems to relate to base url code in the twig?

They all point to http://demo.getgrav.org/deliver-skeleton/blog/portfolio

Same issue with 3 links in bottom right-hand corner ABOUT | PRIVACY POLICY | CONTACT

**Comment by hexplor** [comment]
You're right. I'm going to fix that really soon.
