### ISSUE TITLE
Blog Items Incorrect order

### ISSUE THREAD

**Issue by Vivalldi** [getgrav/grav-skeleton-deliver-site#5]
The list of blog posts are not in order by date. The blog posts had been going fine until recently when one of the posts is lower than the others. The page shows the correct blog date but does not order correctly. 

[SITE](http://heavenlyacresquilts.com)

The blog post in question is titled "Update Successful"

**Comment by hexplor** [comment]
can you send me that post (page .md file) to karol@rockettheme.com, i want to take a look at it.

**Comment by hexplor** [comment]
Well, it appears you didn't specify date in your file ?
Date variable appears to be empty.

**Comment by Vivalldi** [comment]
Even if I have the date set (I removed during testing the bug and sent to you) in the proper format it fails to order that blog post properly.

**Comment by Vivalldi** [comment]
This is also a part of problem #6  
It has to do with the blog.md file (look for a pull request to see differences)
