### ISSUE TITLE
taxonomylist.htm.twig

### ISSUE THREAD

**Issue by davidtew** [getgrav/grav-skeleton-deliver-site#7]
This line is rendering the length of the tax tag word rather than the number of articles tagged.  

> ```
>    <a href="{{ base_url }}/tag:{{ tax|e('url') }}">{{ tax }}  <span>({{ tax|length }})</span></a>
> ```

**Comment by hexplor** [comment]
You are right. I'm going to disable it for a while until i figure out how to find a solution.
