### ISSUE TITLE
Error while editing in Expert mode

### ISSUE THREAD

**Issue by reachcontent** [getgrav/grav-skeleton-deliver-site#9]
I've been fiddling with the skeleton so that's were I mention the following issue but it could be a theme or admin plugin issue.

Steps to reproduce:
1. Open a Page item to edit, switch to Expert mode
2. Modify either some content in Frontmatter or in the main content markdown editor
3. Attempt to save returns the following error message (red banner):

> > > > Validation failed: Invalid input in "Menu""

However it is possible to just modify the main content in Normal mode and then switch to Expert mode for further editing.

Note: at some point, after I had edited the main content, a red dot appeared in the markdown editor on the empty line between the title (##) and the main text.

Configuration: Chromium 45.0 and latest versions of Grav (1rc4) and other plugins.

**Comment by hexplor** [comment]
Looking into that.

**Comment by hexplor** [comment]
I was trying to reproduce that but everything works fine for me. Have you been editing any specific pages ? Do you have latest admin plugin installed ?

**Comment by reachcontent** [comment]
All up-to-date (except for JScomment which is disabled anyway). I have been editing Home, About, Services and as far as I can remember the bug occurred each time.
Have just reproduced it now (on Firefox 42 this time) while trying to edit the Pricing bit, under Services:
1. Select one of the Pages to edit
2. Switch to Expert mode (if not already selected from previous try - Expert mode is not set as default in my admin)
3. Edit either or both Frontmatter and markdown editor
4. Attempt to save changes triggers the error message.

**Comment by hexplor** [comment]
Just want to be 100% sure. Can you test the same issue in antimatter theme ? Is it broken as well ?

**Comment by reachcontent** [comment]
I have been using the Antimatter theme for about 6 months and I installed the Admin plugin as soon as it was available but never had this issue (I started from the skeleton to build a modular One-Page). I just checked and modified some modular pages in Expert mode and all is A-ok.

I just installed and activated the Antimatter theme on the website I started with Deliver skeleton and it seems I have the same bug. Looks as if it comes from something specific to the Deliver theme/skeleton.

**Comment by hexplor** [comment]
Hmm... is it possible for you to send me your whole install zipped to karol(at)rockettheme.com . So i can test it on my install ? Would love to take a look what's wrong..

**Comment by reachcontent** [comment]
Done

**Comment by hexplor** [comment]
Got it !!! 
I think I know what's wrong. This is related to 

```
menu: false
```

Which is included in every markdown file. If i remove that = all ok. I think that option is not needed at all anyways so I will remove it from all files and will release update. Anyways, let me know if removing above from your pages fixes issue for you as well :)

**Comment by reachcontent** [comment]
Ok, I removed that and it solved the issue on the impacted pages I tried. Thank you!

**Comment by simogeo** [comment]
Do you think the commit 2cd7228331a2f6db72df3a83758f3580af1f4e52 can fix this error ? https://github.com/getgrav/grav-plugin-admin/issues/335

Thanks !
